# Пожалуйста, не изменяйте версию плагина.
version: 1
lang: ru
# Время истекания штрафа в секундах.
penalty-max-count: 10000
penalty-expire-time: 604800
penalty-expire-multiplayer: 2.0
penalty-title-fadeIn: 10
penalty-title-stay: 70
penalty-title-fadeOut: 20
# Таблица шаблонов https://javarush.com/quests/lectures/questsyntaxpro.level16.lecture07
penalty-list-date-format: "dd-MM-yyyy HH:mm:ss"
database:
  # Типы базы данных: SQLite, MySQL, MariaDB.
  type: SQLite
  sql:
    # IP адрес для базы данных. (Не относится к SQLite)
    host: localhost
    # Порт для базы данных. (Не относится к SQLite)
    port: '3306'
    # Имя базы данных, в которой будут храниться данные.
    # База данных должна быть уже создана! (Не относится к SQLite)
    database: sp
    # Данные для подключения к базе данных. (Не относится к SQLite)
    username: root
    password: ''
    # Префикс для всех таблиц.
    table-prefix: sp_
    # Можно добавить свои настройки подключения к дате базе, все настройки находятся тут https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
    properties:
      autoReconnect: true
      characterEncoding: utf8
      # Использовать ли SSL для подключения к удаленной базе данных SQL (не относится к SQLite).
      useSSL: false
