name: SimplePenalty
version: '${version}'
main: kz.hxncus.mc.simplepenalty.SimplePenalty
api-version: '1.13'
commands:
  sp:
    permission: "simplepenalty.command"
    aliases:
      - simplepenalty
      - penalty
      - spenalty
