name: SimplePenalty
version: '${version}'
main: kz.hxncus.mc.simplepenalty.SimplePenalty
api-version: '1.13'
commands:
  simplepenalty:
    permission: "simplepenalty.command"
    aliases:
      - sp
      - penalty
      - spenalty
