name: Test compiling against Java 8, 11 and 16

on:
  push:
    branches:
      - development
    paths:
      - "src/**"
      - "build.gradle.kts"
  pull_request:
    branches:
    - development
    paths:
    - "src/**"
    - "build.gradle.kts"

jobs:
  testBuilds:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java-version: [8, 11, 16]
    name: "Compile jar against ${{ matrix.java-version }}"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v4
    - name: "Prepare Java ${{ matrix.java-version }}"
      uses: actions/setup-java@v4
      with:
        distribution: "adopt"
        java-version: "${{ matrix.java-version }}"
    - name: Make build.gradle.kts executable
      run: chmod +x gradlew
    - name: Build jar with Java ${{ matrix.java-version }}
      run: ./gradlew build
